list_frases = [
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best time to plant a tree was twenty years ago. The second best time is now.",
    "Act as if what you do makes a difference. It does.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The journey of a thousand miles begins with one step.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "You miss 100% of the shots you don't take.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only impossible journey is the one you never begin.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Dream big and dare to fail.",
    "What we think, we become.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don't watch the clock; do what it does. Keep going.",
    "Strive not to be a success, but rather to be of value.",
    "Limit your 'always' and your 'nevers'.",
    "You can’t build a reputation on what you are going to do.",
    "The secret of getting ahead is getting started.",
    "Opportunities don't happen. You create them.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Everything you can imagine is real.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The future depends on what you do today.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "What we fear doing most is usually what we most need to do.",
    "It always seems impossible until it’s done.",
    "Your only limit is you.",
    "Don't limit your challenges. Challenge your limits.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "When you feel like quitting, think about why you started.",
    "The best way to predict the future is to create it.",
    "You are enough just as you are.",
    "The only person you are destined to become is the person you decide to be.",
    "In the middle of every difficulty lies opportunity.",
    "Everything you need is already inside you.",
    "Your time is limited, don't waste it living someone else's life.",
    "Don't be afraid to give up the good to go for the great.",
    "If you can dream it, you can achieve it.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only way to do great work is to love what you do.",
    "Success is how high you bounce when you hit bottom.",
    "Don't be pushed by your problems; be led by your dreams.",
    "The future belongs to those who prepare for it today.",
    "To succeed in life, you need three things: a wishbone, a backbone and a funny bone.",
    "Don't count the days, make the days count.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "If you want to achieve greatness, stop asking for permission.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The best revenge is massive success.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Success is not in what you have, but who you are.",
    "If you're going through hell, keep going.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Act as if what you do makes a difference. It does.",
    "The only impossible journey is the one you never begin.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Believe you can and you're halfway there.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Life is either a daring adventure or nothing at all.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Your attitude, not your aptitude, will determine your altitude.",
    "You don't have to see the whole staircase, just take the first step.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "If you want to lift yourself up, lift up someone else.",
    "You can’t use up creativity. The more you use, the more you have.",
    "Life is not about finding yourself. Life is about creating yourself.",
    "Success is how high you bounce when you hit bottom.",
    "Success is the progressive realization of a worthy goal.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "What we fear doing most is usually what we most need to do.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The future depends on what you do today.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Don't be afraid to give up the good to go for the great.",
    "What we think, we become.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "The best way to predict the future is to create it.",
    "The journey of a thousand miles begins with one step.",
    "You are enough just as you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Opportunities don't happen. You create them.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Everything you've ever wanted is on the other side of fear.",
    "Push yourself, because no one else is going to do it for you.",
    "Dream it. Believe it. Build it.",
    "Strive not to be a success, but rather to be of value.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Success doesn't just find you. You have to go out and get it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "Everything you need is already inside you.",
    "It always seems impossible until it's done.",
    "Your only limit is you.",
    "Don't limit your challenges. Challenge your limits.",
    "When you feel like quitting, think about why you started.",
    "Great things never come from comfort zones.",
    "What we fear doing most is usually what we most need to do.",
    "The best way to predict the future is to create it.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Don't count the days; make the days count.",
    "The only impossible journey is the one you never begin.",
    "Success is how high you bounce when you hit bottom.",
    "You are enough just as you are.",
    "The future belongs to those who prepare for it today.",
    "You are never too old to set another goal or to dream a new dream."
]
